### ISSUE TITLE
Wrapping text onto new lines

### ISSUE THREAD

**Issue by ghost** [sosodev/twitchChatCLI#1]
Hi there,

not sure if this project is still active but I use it and I appreciate it! ;)

Just an idea, when the width of the terminal window gets narrow, the text is cut off. I usually have a narrow terminal with this running on the side of the twitch video feed but the chat messages are often cut off at the end of the line instead of wrapping onto the new line.

Related is also that it currently prints the name of the user that wrote the messages several times when the message spans multiple lines, it would be cool if the name was only printed once and the space underneath the initial user name was blank.

Screenshot for reference:

![chatcliwrap](https://user-images.githubusercontent.com/1769510/107390244-cafd5b00-6af7-11eb-8621-2137ee5ea6be.png)

Thanks!

**Comment by sosodev** [comment]
Hi @linuxhype, I'm glad you like the project. I'll definitely take a crack at updating it sometime soon. I'll ping you if I push a new release.

I'm also open to pull requests but the main branch has a lot of work that I never released and probably never will because it goes against the minimalistic style of the original version. I'll probably roll that stuff back before I actually get into making real changes. :)

**Comment by sosodev** [comment]
@linuxhype I just published [v2.0](https://github.com/sosodev/twitchChatCLI/releases/tag/v2.0) that incorporates your feedback and should generally be much more stable. I did just notice, however, that you actually running the older, unpublished update so this might be a little less feature rich but I hope you'll like it none the less.

**Comment by ghost** [comment]
Just tried it, the chat text wrap works well but can you add wrapping to the user chat input as well? That one still cuts off so you can't see the end of the message that you are typing.

Also, im being super nitpicky here but you could change the text wrapping mode so that it breaks up words in a nicer way. Right now it just wraps whenever, but maybe it could wrap entire words instead of splitting them up? Just an idea!

Thanks!
