### ISSUE TITLE
panic: failed to get username from Twitch: Key path not found

### ISSUE THREAD

**Issue by DrSensor** [sosodev/twitchChatCLI#3]
Just got this error after trying it several times
```command
$ ./twitchChatCLI-linux-amd64 drsensor

panic: failed to get username from Twitch: Key path not found

goroutine 1 [running]:
main.main()
	/home/kyle/Projects/twitchChatCLI/main.go:60 +0xc77
```

**Comment by sosodev** [comment]
Hi @DrSensor, when you logged in through Twitch did you happen to decline the permissions requested?

**Comment by sosodev** [comment]
It should show up on https://www.twitch.tv/settings/connections as "streamCLI"

**Comment by DrSensor** [comment]
Yes, then I disconnect `streamCLI` from my dashboard and try again but no luck.
I thought it's related to [Twitch API v5 deprecation (`kraken`)](https://dev.twitch.tv/docs/authentication/#getting-tokens) but nevermind,  it's solved by removing `config.dat` file.

I just noticed that file after looking at the source and have a hard time figuring out where it's saved. I think you should put that in `$XDG_CONFIG_HOME/twitchChatCLI` rather than `$PWD`.

**Comment by sosodev** [comment]
Yep, that's a good thing to be updated. It was a silly decision I made years ago lol.
